sonar.projectKey=monetix-backend
sonar.projectName=Monetix Backend
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9000
sonar.token=${SONAR_TOKEN_MONETIX_BACKEND}

sonar.sources=src
sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/*.test.ts,\
  **/*.spec.ts,\
  **/coverage/**,\
  src/scripts/**

sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.json
