sonar.projectKey=triage-remoto
sonar.projectName=Triage Remoto Distribuido
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9000
sonar.token=${SONAR_TOKEN_TRIAGE}

# Código fuente — todos los servicios y shared
sonar.sources=services,shared,frontend/src,api-gateway
sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/build/**,\
  **/*.test.js,\
  **/*.spec.js,\
  **/coverage/**,\
  **/logs/**

# Tests
sonar.tests=services
sonar.test.inclusions=**/*.test.js,**/*.spec.js
sonar.javascript.lcov.reportPaths=services/analytics-service/coverage/lcov.info

sonar.sourceEncoding=UTF-8
sonar.language=js
