sonar.projectKey=monetix-frontend
sonar.projectName=Monetix Frontend
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9000
sonar.token=${SONAR_TOKEN_MONETIX_FRONTEND}

sonar.sources=src
sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/*.test.ts,\
  **/*.spec.ts,\
  **/*.test.tsx,\
  **/*.spec.tsx,\
  **/coverage/**

sonar.tests=src/utils
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts,**/*.test.tsx,**/*.spec.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Only measure coverage for code that has unit tests
sonar.coverage.exclusions=\
  src/pages/**,\
  src/components/**,\
  src/context/**,\
  src/services/**,\
  src/store/**,\
  src/layouts/**,\
  src/hooks/**,\
  src/config/**,\
  src/types/**,\
  src/main.tsx,\
  src/App.tsx

sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.json
